"""create structural tables

Revision ID: dfe8b83b9b14
Revises: 
Create Date: 2026-08-31 16:09:47.994631

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dfe8b83b9b14'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dimensions',
    sa.Column('dimension_id', sa.String(), nullable=False),
    sa.Column('member_type', sa.String(), nullable=False),
    sa.Column('dim', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("member_type IN ('col', 'beam', 'wall', 'slab')", name='ck_dimensions_member_type'),
    sa.PrimaryKeyConstraint('dimension_id'),
    sa.UniqueConstraint('dimension_id', 'member_type', name='uq_dimensions_id_type')
    )
    op.create_table('grids',
    sa.Column('grid_axis', sa.String(), nullable=False),
    sa.Column('grid_label', sa.String(), nullable=False),
    sa.Column('coordinate_mm', sa.Integer(), nullable=False),
    sa.CheckConstraint("grid_axis IN ('x', 'y')", name='ck_grids_axis'),
    sa.PrimaryKeyConstraint('grid_axis', 'grid_label')
    )
    op.create_table('materials',
    sa.Column('material_id', sa.String(), nullable=False),
    sa.Column('material_name', sa.String(), nullable=False),
    sa.Column('material_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('material_id')
    )
    op.create_table('storeys',
    sa.Column('storey_id', sa.String(), nullable=False),
    sa.Column('storey_name', sa.String(), nullable=False),
    sa.Column('elevation_mm', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('storey_id')
    )
    op.create_table('zones',
    sa.Column('zone_id', sa.String(), nullable=False),
    sa.Column('zone_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('zone_id')
    )
    op.create_table('members',
    sa.Column('member_id', sa.String(), nullable=False),
    sa.Column('member_type', sa.String(), nullable=False),
    sa.Column('storey_id', sa.String(), nullable=False),
    sa.Column('dimension_id', sa.String(), nullable=False),
    sa.Column('material_id', sa.String(), nullable=False),
    sa.Column('zone_id', sa.String(), nullable=False),
    sa.Column('geometry_points', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['dimension_id', 'member_type'], ['dimensions.dimension_id', 'dimensions.member_type'], name='fk_members_dimension_type'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.material_id'], ),
    sa.ForeignKeyConstraint(['storey_id'], ['storeys.storey_id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.zone_id'], ),
    sa.PrimaryKeyConstraint('member_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    op.drop_table('zones')
    op.drop_table('storeys')
    op.drop_table('materials')
    op.drop_table('grids')
    op.drop_table('dimensions')
    # ### end Alembic commands ###
